### ISSUE TITLE
java.lang.NoSuchFieldError: UTF8_CHARSET

### ISSUE THREAD

**Issue by br4in1** [cloudinary/cloudinary_java#117]
When i try to upload an image file, i receive an error saying : 

```
Caused by: java.lang.NoSuchFieldError: UTF8_CHARSET
	at com.cloudinary.http44.UploaderStrategy.callApi(UploaderStrategy.java:91)
	at com.cloudinary.Uploader.callApi(Uploader.java:34)
	at com.cloudinary.Uploader.upload(Uploader.java:76)
	at com.cloudinary.Uploader.upload(Uploader.java:68)
	at Controllers.Login_formController.UploadPhoto(Login_formController.java:335)
	... 55 more
```

Thank you

**Comment by br4in1** [comment]
Turns out I was using and old version of MIME library, deleting the old one using the latest fixed the issue
