### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.http.entity.ContentType.create

### ISSUE THREAD

**Issue by senlinmuvs** [cloudinary/cloudinary_java#122]
**Version:**
com.cloudinary:cloudinary-http44:1.18.0

**Exception:**
`java.lang.NoSuchMethodError: org.apache.http.entity.ContentType.create(Ljava/lang/String;[Lorg/apache/http/NameValuePair;)Lorg/apache/http/entity/ContentType;
	at org.apache.http.entity.mime.MultipartEntityBuilder.buildEntity(MultipartEntityBuilder.java:209)
	at org.apache.http.entity.mime.MultipartEntityBuilder.build(MultipartEntityBuilder.java:230)
	at com.cloudinary.http44.UploaderStrategy.callApi(UploaderStrategy.java:127)
	at com.cloudinary.Uploader.callApi(Uploader.java:30)
	at com.cloudinary.Uploader.destroy(Uploader.java:231)`

**Comment by senlinmuvs** [comment]
I changed to the http43, it works! But why?
com.cloudinary:cloudinary-**http43**:1.18.0

**Comment by idobarnoam** [comment]
@senlinmuvs This could mean there is a library conflict. Probably some other library that is used is also pulling apache's client with a different version (or something similar).

If you are not exactly sure you could send us the build.gradle files (or pom.xml if using maven) and we could take a look.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
