### ISSUE TITLE
java.net.UnknownHostException: api.cloudinary.com: unknown error

### ISSUE THREAD

**Issue by pawsaw** [cloudinary/cloudinary_java#138]
While using the JavaSdk (Kotlin in Spring context), I'll get this error. A couple of days ago everything has been working... no code change throughout this time period.

build.gradle: compile('com.cloudinary:cloudinary-http44:1.18.0')

java.net.UnknownHostException: api.cloudinary.com: unknown error
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_66]
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_66]
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_66]
at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[na:1.8.0_66]
at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_66]
at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_66]

**Comment by pawsaw** [comment]
Hi @aditimadan-Cloudinary 

Yes, it happens on upload. Since we're using cloudinary for a month, it doesn't happen before. We haven't changed our code.

The versions are:

com.cloudinary:cloudinary-http44:1.18.0
java: 1.8.0_66

The code (kotlin) is nothing special...

the initialization...

    lateinit var cloudinary: Cloudinary

    @PostConstruct
    fun init() {
        cloudinary = Cloudinary(ObjectUtils.asMap(
                "cloud_name", cloudName,
                "api_key", apiKey,
                "api_secret", apiSecret))
    }`

and the upload itself...

`cloudinary.uploader().upload(tmpFile, ObjectUtils.emptyMap())`

**Comment by aditimadan-Cloudinary** [comment]
This exception means it has trouble resolving the hostname. Can you try the suggestions mentioned in this link and see if it works: https://stackoverflow.com/questions/6484275/java-net-unknownhostexception-invalid-hostname-for-server-local
