### ISSUE TITLE
ClassNotFoundException (Tomcat 7)

### ISSUE THREAD

**Issue by ImperionGameDev** [cloudinary/cloudinary_java#21]
Hi,

I got this error while uploading image. Should i configure something at servlet xmls or download HttpClient source code.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at com.cloudinary.strategies.StrategyLoader.load(StrategyLoader.java:11)
	at com.cloudinary.strategies.StrategyLoader.find(StrategyLoader.java:20)
	at com.cloudinary.Cloudinary.loadStrategies(Cloudinary.java:74)
	at com.cloudinary.Cloudinary.<init>(Cloudinary.java:88)
	at CloudTest.<init>(CloudTest.java:19)
	at CloudTest.main(CloudTest.java:24)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.methods.HttpUriRequest
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

**Comment by tocker** [comment]
This is a *classpath* issue. The solution depends on your environment.

[Maven](https://maven.apache.org/) is the easiest solution as it will load the required libraries. IDEs such as eclipse and intelliJ support maven.

**For manual setup**
* download the libraries from the [apache download page](https://hc.apache.org/downloads.cgi)
* extract the archive
* add the lib folder in the extracted location to your classpath
