### ISSUE TITLE
java.lang.RuntimeException: Stale request

### ISSUE THREAD

**Issue by benmarten** [cloudinary/cloudinary_java#25]
Since a few days I am seeing this issue in our android application?

Any help is appreciated:

	06-20 14:59:45.959  21560-22039/com.colibriapps.foodlr E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-3085
	    Process: com.colibriapps.foodlr, PID: 21560
	    java.lang.RuntimeException: Stale request - reported time is 2015-06-20 12:59:41 +0000 which is more than 1 hour ago
	            at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:101)
	            at com.cloudinary.Uploader.callApi(Uploader.java:22)
	            at com.cloudinary.Uploader.upload(Uploader.java:55)
	            at com.colibriapps.foodlr.controller.offer.OfferDishFragment.uploadImage(OfferDishFragment.java:1033)
	            at com.colibriapps.foodlr.controller.offer.OfferDishFragment.access$500(OfferDishFragment.java:86)
	            at com.colibriapps.foodlr.controller.offer.OfferDishFragment$15.run(OfferDishFragment.java:969)
	            at java.lang.Thread.run(Thread.java:818)

**Comment by taragano** [comment]
Hi,
Please note that the signature is based on the timestamp and is valid for 1 hour. Therefore, you should make sure that the signature is being refreshed if the window can stay opened for a long time.
For more information:
http://support.cloudinary.com/entries/23139647-I-got-a-Stale-request-error-for-my-upload-API-call-what-does-it-mean-

**Comment by benmarten** [comment]
Yes thanks, It was indeed the wrong time of my android device!
