### ISSUE TITLE
Not uploading from local directory

### ISSUE THREAD

**Issue by amanpareek93** [cloudinary/cloudinary_java#30]
I am using cloudinary-taglib-1.2.1,cloudinary-core-1.2.1,cloudinary-http44-1.2.1,

Its working perfectly fine with http url but not with local directory path.

 uploadResult=cloudinary.uploader().upload(/home/***/im.jpg,options);----{Runtime Exception}

Exception in thread "main" java.lang.RuntimeException: Invalid URL for upload
	at com.cloudinary.http44.UploaderStrategy.callApi(UploaderStrategy.java:140)
	at com.cloudinary.Uploader.callApi(Uploader.java:22)
	at com.cloudinary.Uploader.upload(Uploader.java:55)
	at com.snapdeal.reviews.client.api.impl.ImageClientServiceImpl.uploadImage(ImageClientServiceImpl.java:73)
	at com.snapdeal.reviews.client.api.impl.ImageClientServiceImpl.main(ImageClientServiceImpl.java:102)

**Comment by itaibenari** [comment]
@amanpareek93 
This would probably mean that the if branch around https://github.com/cloudinary/cloudinary_java/blob/master/cloudinary-http44/src/main/java/com/cloudinary/http44/UploaderStrategy.java#L96 fails for some reason. Are you able to debug and see if that's the case?
Does it fail for every path or just one?
If just one - can you share the full path?

**Comment by amanpareek93** [comment]
It was failing in every local path , later on , I used fileinputstream and
convert the file f = new file(path) ... f object into byte array and passed
the bytearray as uploader().upload(bytearray) method . And it worked . Dont
know how, but it works in this way only in my case .

**Comment by taragano** [comment]
Hi,
I'm closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
