### ISSUE TITLE
Cloudinary uploading pictures / Missing required parameter - file

### ISSUE THREAD

**Issue by janusnjanus** [cloudinary/cloudinary_java#42]
I am trying to use Cloudinary in Android Studio, uploading pictures, and videos but getting an error as it shows in the stack trace : 
Caused by: java.lang.RuntimeException: Missing required parameter - file
as soon i chose a picture from the intent gallery and the progress dialog box pop up, it frees then the app shutdown, will it just prompt that it will but it goes back to the upload activity window.

I've tried to apply the same code for Video, but i got the same issue, which i am still trying to find out and understand how the right syntax works.

My code is : 
`import android.app.ProgressDialog;
import android.content.Intent;
import android.net.Uri;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.StrictMode;
import android.provider.MediaStore;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;

import java.io.IOException;

public class Upload extends AppCompatActivity implements View.OnClickListener {

    public static final int RESULT_LOAD_IMAGE = 1;
    ImageView imgToUpload;
    Button buttonUploadSubmit;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.upload);
        if (android.os.Build.VERSION.SDK_INT > 9) {
            StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();
            StrictMode.setThreadPolicy(policy);
        }

        imgToUpload = (ImageView) findViewById(R.id.imgToUpload);
        buttonUploadSubmit = (Button) findViewById(R.id.ButtonUploadSubmit);

        imgToUpload.setOnClickListener(this);
        buttonUploadSubmit.setOnClickListener(this);

    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.imgToUpload:
                Intent galleryIntent = new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
                startActivityForResult(galleryIntent, RESULT_LOAD_IMAGE);

                break;
            case R.id.ButtonUploadSubmit:
                UploadTask uploadTask = new UploadTask();
                uploadTask.execute(String.valueOf(imgToUpload));

                break;
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Uri selectedImage = data.getData();
        imgToUpload.setImageURI(selectedImage);
    }

    class UploadTask extends AsyncTask<String, Void, Void>{

        ProgressDialog progressDialog;

       @Override
       protected void onPreExecute(){
            progressDialog = new ProgressDialog(Upload.this);
           progressDialog.setTitle("Upload in Progress ...");
           progressDialog.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);
           progressDialog.setMax(100);
           progressDialog.setProgress(0);
           progressDialog.show();
       }

        @Override
        protected Void doInBackground(String... params) {
            Cloudinary cloudinary = new Cloudinary(ObjectUtils.asMap(
                    "cloud_name", "xxxxx",
                    "api_key", "xxxxxxxxxxxx",
                    "api_secret", "xxxxxxxxxxxxxxxxx"));
            try {
                cloudinary.uploader().upload(imgToUpload,
                        ObjectUtils.asMap("resource_type", "image"));
            } catch (IOException e) {
                e.printStackTrace();
            }

            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
        }
    }

}`

the stacktrace is:

`03-14 08:44:13.179 14589-16685/net.we4x4.we4x4 E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                 Process: net.we4x4.we4x4, PID: 14589
                                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                     at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:841)
                                                                  Caused by: java.lang.RuntimeException: Missing required parameter - file
                                                                     at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:106)
                                                                     at com.cloudinary.Uploader.callApi(Uploader.java:22)
                                                                     at com.cloudinary.Uploader.upload(Uploader.java:55)
                                                                     at net.we4x4.we4x4.Upload$UploadTask.doInBackground(Upload.java:90)
                                                                     at net.we4x4.we4x4.Upload$UploadTask.doInBackground(Upload.java:69)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:841) `

I am not sure if there is something wrong in my code ( syntax ) or i am missing something !?

**Comment by taragano** [comment]
Hi,

Correct me if I'm wrong, but it seems from [StackOverflow](http://stackoverflow.com/questions/35989605/cloudinary-missing-required-parameter) that you've managed to find a solution for this?
If not, please let us know.

**Comment by janusnjanus** [comment]
I apologize for the late reply, use i did find a solution for this problem, i forgot to update the post here, but i did manage to update StackOverflow  post as @taragano posted the link, thank you again for your notice.
